# Tensors in ml:-

A tensor is a data container that can store numbers in multiple dimensions. In ML, tensors are used to represent things like datasets, images, text, audio, and model parameters.
| Type          | Dimensions | Example            | Common ML use                    |
| ------------- | ---------: | ------------------ | -------------------------------- |
| **Scalar**    |         0D | `5`                | Single value                     |
| **Vector**    |         1D | `[1, 2, 3]`        | Features of one sample           |
| **Matrix**    |         2D | `[[1,2], [3,4]]`   | Dataset / tabular data           |
| **3D Tensor** |         3D | `[[[1,2], [3,4]]]` | One RGB image / sequence data    |
| **4D Tensor** |         4D | Batch of images    | Multiple images in deep learning |


# Types of tensor:-


no. of axis = rank = dimension 

1) scaler or 0d tensor

In [1]:
import numpy as np 
a=np.array(4)
print(a)

4


checking dimension by .dim

In [2]:
a.ndim

0

2. vector or 1D tensors

In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
a.ndim

1

3. matrix or 2D tensor

In [4]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print( a)
a.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

4. 3D tensor

![alt text](<Screenshot 2026-09-21 201356.png>)

In [5]:
import numpy as np
a= np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(a)
a.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3